name: Get package version
description: Reads "version" field from package.json
outputs:
  version-json:
    description: The JSON value of the "version" field from package.json
    value: ${{ steps.version.outputs.value }}
  version:
    description: The value of the "version" field from package.json
    value: ${{ steps.version.outputs.value }}
runs:
  using: composite
  steps:
    - id: json-version
      uses: ./get-package-field-value
      with:
        field: version
    - id: version
      uses: ./unquotify
      with:
        json: ${{ steps.json-version.outputs.value }}
