name: Action tests
on: [push]
jobs:

  compare-json:
    name: Compare JSON
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./compare-json/tests

  get-npm-registry-versions:
    name: Get npm registry versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./get-npm-registry-versions/tests

  jsonify:
    name: JSONify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./jsonify/tests

  unquotify:
    name: Unquotify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./unquotify/tests

  build-version-tag:
    name: Build version tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./build-version-tag/tests

  get-package-field-value:
    name: Get package field value
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./get-package-field-value/tests

  get-repository-version-tags:
    name: Get repository version tags
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./get-repository-version-tags/tests

  array-includes-value:
    name: Array includes value
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./array-includes-value/tests

  repository-has-tag:
    name: Repository has tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./repository-has-tag/tests

  delete-repository-tag:
    name: Delete repository tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./delete-repository-tag/tests

  tag-current-commit:
    name: Tag current commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./tag-current-commit/tests

  npm-registry-has-version:
    name: NPM registry has version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./npm-registry-has-version/tests

  publish-to-npm:
    name: Publish to NPM registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./publish-to-npm/tests

#    !!
#  add-new-version-tag:
#    name: Use package version as a tag to add to the repository if it does not exist yet
#    runs-on: ubuntu-latest
#    needs: [get-package-version, array-includes-value]
#    if: needs.array-includes-value.outputs.includes == 'false'
#    steps:
#      - uses: actions/checkout@v3
#      - id: build-version-tag
#        uses: ./build-version-tag
#        with:
#          version: ${{ needs.get-package-version.outputs.version }}
#      - id: tag-current-commit
#        uses: ./tag-current-commit
#        with:
#          tag: ${{ steps.build-version-tag.outputs.version-tag }}
