name: Action tests
on: [push]
jobs:
  get-package-version:
    name: Get package version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: get-package-version
        uses: ./get-package-version
      - run: 'echo "package version: ${{ steps.get-package-version.outputs.version }}"'
        shell: sh
  get-repository-version-tags:
    name: Get repository version tags
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: get-repository-version-tags
        uses: ./get-repository-version-tags
      - run: "echo 'repository version tags: ${{ steps.get-repository-version-tags.outputs.tags }}'"
        shell: sh
