name: Test actions
on: [push]
jobs:
  get-package-version:
    name: Get package version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: get-package-version
        uses: ./get-package-version
      - run: 'echo "package version: ${{ steps.get-package-version.outputs.version }}"'
        shell: bash
